export const USER_LOGIN_ACCESS = 'USER_LOGIN_ACCESS'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_ACCESS = 'USER_REGISTER_ACCESS'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_LOGOUT = 'USER_LOGOUT'

